name: Main Configuration file for orchestration of pipeline

on:
  workflow_call:

jobs:
  Run-Tests:
    if: ${{ GITHUB.event_name == 'pull_request' }}
    uses: ts-software-solutions/shared-workflows/.github/workflows/build-test.yml@main
    secrets: inherit

  Build-And-Publish:
    if: ${{ GITHUB.event_name != 'pull_request' }}
    uses: ts-software-solutions/shared-workflows/.github/workflows/build-test.yml@main
    secrets: inherit
    with:
      build-test: 'build'

  Deploy-to-DEV:
    if: ${{ GITHUB.event_name != 'pull_request' && GITHUB.ref_name != 'main'}}
    needs: [Build-And-Publish]
    uses: ts-software-solutions/shared-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with: 
      mule-env: 'DEV'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}
  
  Deploy-to-UAT:
    if: ${{ GITHUB.event_name != 'pull_request' && GITHUB.ref_name != 'main'}}
    needs: [Build-And-Publish, Deploy-to-Dev]
    uses: ts-software-solutions/shared-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with: 
      mule-env: 'UAT'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}
  
  Deploy-to-PROD:
    if: ${{ GITHUB.event_name != 'pull_request' && always() && (needs.Deploy-to-Dev.result == 'success' || needs.Deploy-to-UAT.result == 'success') }}
    needs: [Build-And-Publish, Deploy-to-Dev, Deploy-to-UAT]
    uses: ts-software-solutions/shared-workflows/.github/workflows/deploy.yml@main
    secrets: inherit
    with: 
      mule-env: 'PROD'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}

  Branch-Cleanup:
    if: ${{ GITHUB.event_name != 'pull_request' }}
    needs: [Build-And-Publish, Deploy-to-PROD]
    uses: ts-software-solutions/shared-workflows/.github/workflows/branch-cleanup.yml@main
    secrets: inherit 
    with:
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}

  Create-Tag:
    if: ${{ GITHUB.event_name != 'pull_request' }}
    needs: [Build-And-Publish, Deploy-to-PROD, Branch-Cleanup]
    uses: ts-software-solutions/shared-workflows/.github/workflows/create-tag.yml@main
    secrets: inherit 
    with:
      tag-name: ${{ needs.Build-And-Publish.outputs.short-sha }}