name: I created this for test purposes only

on:
  workflow_dispatch:
    inputs:
      version-number:
        type: string
        description: The version you would like to add to the avioconsulting registry e.g. 1.0.4222401

jobs:
  things-to-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      - name: Get Release files from release
        uses: robinraju/release-downloader@v1.8
        with: 
          tag: "v${{ inputs.version-number}}"
          fileName: "*"
          tarBall: false
          zipBall: true
          extract: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List all files
        run: |
          ls -la
          unzip shared-workflows-v${{ inputs.version-number }}.zip -d source_code
          ls -la source_code

      - name: read testing
        run: |
          os=darwin
          arch=arm64
          BINARY=$(echo "11f84edda4c5c4add7f9c876e61ecd3ff322ce5b25cb80dbca288e4feffbc878  terraform-provider-apm_v0.0.1_darwin_arm64.zip" | grep ".*$os_$arch.*")
          IFS='   '
          read -r SHA FILE_NAME <<< "$BINARY" 
          echo "SHA: $SHA"
          echo "FILE_NAME: $FILE_NAME"